### ISSUE TITLE
[Melhora] Mudar para outro server Nitter, incluso um propio, para o uso

### ISSUE THREAD

**Issue by BloodDragooner2** [ocamposbio/blueskybot#1]
Se eu nao me engano, fazer scraping de qualquer server nitter nao eh recomendado, ja que para de funcionar em algum ponto por tanta gente usando ele.

**Comment by ocamposbio** [comment]
Até ontem, o Nitter foi a única forma que eu encontrei para ter acesso aos tweets sem usar VPN

O tutor do Pépito soltou uma API dele e eu estou estudando para ver como posso usar :)

**Comment by BloodDragooner2** [comment]
Boa sorte!
